runtime: python39 # or another supported version
entrypoint: gunicorn -b :$PORT personal.wsgi

instance_class: F2

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /static
  static_dir: /static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto